BINANCE_API_KEY = 'nLb32IWGecG6j4CvUOYXr8GddJDMmoI6awz6oEwXx3J1Q0PqFQzR4J7AyZxRa5ru'
BINANCE_API_SECRET = 'TBYQdZ4DMgjjmq3gnaLsPtmUUAzGx9f7ELb8dqACKt0ZYGhXoHPuvlGhCvyBIuuy'
INITIAL_DEPOSIT_USDT = 100000
LEVERAGE = 25
RISK_PER_TRADE_PCT = 0.1
TRADING_PAIRS = [
    # 'PEPE/USDT',
    # 'DOGE/USDT',
    # 'BNB/USDT',
    # 'FET/USDT',
    # 'JUP/USDT',
    # 'SOL/USDT',
    # 'LTC/USDT',
    # 'MATIC/USDT',
    # 'MANTA/USDT',
    # 'APT/USDT',
    # 'ARB/USDT',
    'ETH/USDT',
    'BTC/USDT',
    # 'PEOPLE/USDT',
    # 'WIF/USDT',
    # 'TON/USDT',
    # 'BONK/USDT'
]
ORDER_MONITOR_INTERVAL = 5
TRADING_FEES = {
    'binance': 0.001,
    'kraken': 0.0026
}
OVERBOUGHT_THRESHOLD = 70
OVERSOLD_THRESHOLD = 30
ADX_MIN = 30
VOL_MA_MULTIPLIER = 1.8
MACD_HIST_SLOPE_MIN = 0.0
ENTRY_COOLDOWN_BARS = 6
TIMEFRAME = '4h'
BACKTEST_START = '2024-01-01 00:00:00'
BACKTEST_END = '2025-07-30 23:59:59'
LOG_LEVEL = 'INFO'
TAKE_PROFIT_PERCENTAGE = 0.01
STOP_LOSS_PERCENTAGE = 0.005
EXCLUDE_TRADING_PAIRS = [
    'BUSDUSDT',
    'USDCUSDT',
    'DAIUSDT',
    'FDUSDUSDT',
    'PAXUSDT',
    'TUSDUSDT',
    'EURUSDT'
]

# Strategy switches
USE_BREAKOUT_STRATEGY = True
DONCHIAN_PERIOD = 30
ATR_PERIOD = 14
ATR_MULT_STOP = 1.2
ATR_MULT_TP = 4.5
MIN_ATR_PCT = 0.006
USE_TRAILING_STOP = True
ATR_MULT_TRAIL = 2.0
ALLOW_SHORTS = True
BREAKOUT_ATR_BUFFER_MULT = 0.1
DONCHIAN_WIDTH_MIN_PCT = 0.015
USE_BREAK_EVEN = True
BREAK_EVEN_ATR_MULT = 1.0

TELEGRAM_BOT_TOKEN = '6648604496:AAG5BP9vk73e89dPzDtM7t4O2B6-hWYEq8E'
TELEGRAM_CHAT_ID = '-1002096239265'
